version: "3.9"
services:
  flask:
    build: ./flask
    ports:
      - '5000:5000'
    volumes:
      - ./flask:/app
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: development